[env]
TERM = "xterm-256color"


# [general]
# import = [
#     "~/.config/alacritty/themes/themes/one_dark.toml"
# ]

# [general]
# import = [
#     "~/.config/alacritty/themes/themes/solarized_dark.toml"
# ]

# [general]
# import = [
#     "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
# ]

[font]
size = 14

#family = "Hack Nerd Font Mono"
#family = "JetBrains Mono"
#family = "JetBrainsMono Nerd Font Mono"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
